[package]
name = "push-relabel-max-flow"
version = "0.1.0"
authors = ["lbrande <lovbra00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
